POST http://localhost:8080/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 0.0
    }
  ]
}

###
POST http://localhost:8080/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 25000.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 0.0
    }
  ]
}

###
POST http://localhost:8080/tax/calculations
Content-Type: application/json

{
  "totalIncome": 500000.0,
  "wht": 0.0,
  "allowances": [
    {
      "allowanceType": "donation",
      "amount": 200000.0
    }
  ]
}

###
POST http://localhost:8080/tax/calculations/upload-csv
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="taxFile"; filename="taxes.csv"
Content-Type: text/csv

< ./taxes.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--